### PR TITLE
readme: fix example code

### PR DESCRIPTION
**Pull request by gabbersepp**
- fix missing semi colon
- batch update with the original iEnumerable does not work because of "multiple enumeration" thus store the masked result in a new list

### CODE REVIEW

**Comment by gabbersepp** [comment]
Also the signature of "UpdateRows" seems to have beeen changed back in time. The "batch size" is not the last parameter anymore

**Comment by Steveiwonder** [comment]
Heya, I'm closing this pull request in favour of changes made in https://github.com/Steveiwonder/DataMasker/pull/27. The changes I've made to this PR will fix this issue. Thanks for bringing this to my attention.

**Comment by gabbersepp** [comment]
Hey, it is ok for me. Do you want me to merge the master into this pr in order to resolve  merge conflicts?

Thanks for merging the other one!

**Comment by Steveiwonder** [comment]
Cool, everything is now merged and built. You should be able to find all the fixes in https://www.nuget.org/packages/DataMasker/1.0.68

**Pull request closed without merging**
